### ISSUE TITLE
Asgore causing crashes

### ISSUE THREAD

**Issue by UTNerd24** [RedSpah/HATE#1]
I have had no problem running this program, however most dialogue involving Asgore's portrait causes crashes saying something about an invalid expression.
What do?

**Comment by redspah** [comment]
What I _suspect_ happens is that Asgore's sprite just doesn't have enough animation frames (since each expression is just a separate frame of animation), dialogue tries to access frames beyond the available number and thus crashes the game.

I don't think too much can be done.

Except corrupting the whole thing again.
